### ISSUE TITLE
Is it possible to turn off some typescript-formatter rules?

### ISSUE THREAD

**Issue by BenceSzalai** [witcher112/eslint-plugin-typescript-formatter#2]
Hi!

I've seen your [comment](https://github.com/typescript-eslint/typescript-eslint/issues/1824#issuecomment-1379843387) and came to find some replacement for the broken `@typescript-eslint/indent` rule.

My problem with this however that it tries to "fix" so many other things as well.

Is it possible do you think to somehow turn off the rules of typescript-formatter that are not related to indentation?

Afaics the configuration for those rules are mostly `boolean` enforcing either one or another way of duing thins. I found no option to ignore for example spacing around braces etc.

Thanks!

**Comment by witcher112** [comment]
Hi,

unfortunately, we're limited to things that TypeScript built-in formatter offers. You can play around with the configuration. One tip that might work for you is that fields besides accepting `boolean` values, accept `undefined` as well (I suppose it can disable the rule in some cases).

Please let me know if that works for you!
